# Generated by Django 3.2.24 on 2024-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderplaced_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
