# Generated by Django 3.2.24 on 2024-03-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderplaced_payment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
