# Generated by Django 3.2.24 on 2024-03-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_zipcode_customer_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
